config/routes.rb
Rails.application.routes.draw do
   devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#index'
  get 'contact',to: 'pages#contact'
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/page_controller.rb
class PageController<application_controller

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
private
def sign_up_params
params.require(:user).permit(
:email,
:password,
:password_confirmation,
:username,
:firstname,
:lastname
)
end
def account_update_params
params.require(:user).permit(
:email,
:password,
:password_confirmation,
:current_password,
:username,
:firstname,
:lastname
)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_foot.html.erb
<% if current_user  %>
<footer class="footer-distributed">
<div class="footer-left">
<h3>Company<span>logo</span></h3>
<p class="footer-links">
<a href="#">Home</a>
·
<a href="#">Blog</a>
·
<a href="#">Pricing</a>
·
<a href="#">About</a>
·
<a href="#">Faq</a>
·
<a href="#">Contact</a>
</p>
<p class="footer-company-name">Company Name &copy; 2015</p>
<div class="footer-icons">
<a href="#"><i class="fa fa-facebook"></i></a>
<a href="#"><i class="fa fa-twitter"></i></a>
<a href="#"><i class="fa fa-linkedin"></i></a>
<a href="#"><i class="fa fa-github"></i></a>

2 
</div>
</div>
<div class="footer-right">
<p>Contact Us</p>
<form action="#" method="post">
<input type="text" name="email" placeholder="Email" />
<textarea name="message" placeholder="Message"></textarea>
<button>Send</button>
</form>
</div>
</footer>
<% else %>
<footer class="footer-distributed">
<div class="footer-right">
<a href="#"><i class="fa fa-facebook"></i></a>
<a href="#"><i class="fa fa-twitter"></i></a>
<a href="#"><i class="fa fa-linkedin"></i></a>
<a href="#"><i class="fa fa-github"></i></a>
</div>
<div class="footer-left">
<p class="footer-links">
·
<a class="page-scroll" href="#portfolio">Contact Us</a>
·
<a class="page-scroll" href="#services">About Us</a>
·
</p>
<p> </p>
</div>
</footer>
<% end %>

app/views/layouts/_nav.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Hello Rails" ,root_path ,class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
       <% if !current_user  %>
      <li class="nav-item active">
       <%= link_to "Sign up",new_user_registration_path ,class: "nav-link" %>
      </li>
      <li class="nav-item ">
        <%= link_to "Sign in",new_user_session_path ,class: "nav-link" %>
      </li>
        <% else  %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%=current_user.username %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Edit Password", edit_user_registration_path ,class: "dropdown-item" %>
     <!--      <div class="dropdown-divider">
            
          </div> -->
           <%= link_to "Sign out",destroy_user_session_path ,class: "dropdown-item" ,method: :delete %>
        </div>
      </li>
      <% end %>
      <li class="nav-item">
         <%= link_to "Contact Us",contact_path,class: "nav-link" %>
      </li>
       <li class="nav-item">
         <%= link_to "About",pages_about_path ,class: "nav-link" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div>
 <%=  icon('fas', 'flag') %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hellorails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/nav" %>
    <%= bootstrap_flash %>
    <div class="container-">
      <%= yield %>
    </div>
    <%= render 'layouts/foot' %>
  </body>
</html>

app/views/page/index.html.erb
<h1>Hello world</h1>

app/views/pages/about.html.erb
<div class="row">
 <div class="col-lg-12 text-center">
 <h1>About Us</h1>
 <p class="lead">Test Text</p>
 <ul class="list-unstyled">
 <li>List Item</li>
 <li>List Item 2</li>
 </ul>
 </div>
</div>

app/views/pages/contact.html.erb
<div class="row">
 <div class="col-lg-12 text-center">
 <h1>Contact Us</h1>
 <p class="lead">Test Text</p>
 <ul class="list-unstyled">
 <li>List Item</li>
 <li>List Item 2</li>
 </ul>
 </div>
</div>

app/views/pages/index.html.erb
<!--Index Page-->
 <div class="row">
 <!-- Blog Post Content Column -->
 <div class="col-lg-8">
 <!-- Blog Post -->
 <!-- Title -->
 <h1>Blog Post Title</h1>

2 
 <!-- Author -->
 <p class="lead">
 by <a href="#">Start Bootstrap</a>
 </p>
 <hr>
 <!-- Date/Time -->
 <p><span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>
 <hr>
 <!-- Preview Image -->
 <img class="img-responsive" src="http://placehold.it/900x300" alt="">
 <hr>
 <!-- Post Content -->
 <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero,
obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi
eos magni recusandae laborum minus inventore?</p>
 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum
quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat.
Temporibus, voluptatibus.</p>
 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto
blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat
perspiciatis. Enim, iure!</p>
 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas
placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem
obcaecati?</p>
 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo,
aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam
recusandae? Qui, necessitatibus, est!</p>
 <hr>
 <!-- Blog Comments -->
 <!-- Comments Form -->
 <div class="well">
 <h4>Leave a Comment:</h4>
 <form role="form">
 <div class="form-group">
 <textarea class="form-control" rows="3"></textarea>
 </div>
 <button type="submit" class="btn btn-primary">Submit</button>
 </form>
 </div>
 <hr>

3 
 <!-- Posted Comments -->
 <!-- Comment -->
 <div class="media">
 <a class="pull-left" href="#">
 <img class="media-object" src="http://placehold.it/64x64" alt="">
 </a>
 <div class="media-body">
 <h4 class="media-heading">Start Bootstrap
 <small>August 25, 2014 at 9:30 PM</small>
 </h4>
 Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
 </div>
 </div>
 <!-- Comment -->
 <div class="media">
 <a class="pull-left" href="#">
 <img class="media-object" src="http://placehold.it/64x64" alt="">
 </a>
 <div class="media-body">
 <h4 class="media-heading">Start Bootstrap
 <small>August 25, 2014 at 9:30 PM</small>
 </h4>
 Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
 <!-- Nested Comment -->
 <div class="media">
 <a class="pull-left" href="#">
 <img class="media-object" src="http://placehold.it/64x64" alt="">
 </a>
 <div class="media-body">
 <h4 class="media-heading">Nested Start Bootstrap
 <small>August 25, 2014 at 9:30 PM</small>
 </h4>
 Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
 </div>
 </div>
 <!-- End Nested Comment -->
 </div>
 </div>
 </div>

4 
 <!-- Blog Sidebar Widgets Column -->
 <div class="col-md-4">
 <!-- Blog Search Well -->
 <div class="well">
 <h4>Blog Search</h4>
 <div class="input-group">
 <input type="text" class="form-control">
 <span class="input-group-btn">
 <button class="btn btn-default" type="button">
 <span class="glyphicon glyphicon-search"></span>
 </button>
 </span>
 </div>
 <!-- /.input-group -->
 </div>
 <!-- Blog Categories Well -->
 <div class="well">
 <h4>Blog Categories</h4>
 <div class="row">
 <div class="col-lg-6">
 <ul class="list-unstyled">
 <li><a href="#">Category Name</a>
 </li>
 <li><a href="#">Category Name</a>
 </li>
 <li><a href="#">Category Name</a>
 </li>
 <li><a href="#">Category Name</a>
 </li>
 </ul>
 </div>
 <div class="col-lg-6">
 <ul class="list-unstyled">
 <li><a href="#">Category Name</a>
 </li>
 <li><a href="#">Category Name</a>
 </li>
 <li><a href="#">Category Name</a>
 </li>
 <li><a href="#">Category Name</a>
 </li>
 </ul>
 </div>
 </div>
 <!-- /.row -->
 </div>
 <!-- Side Widget Well -->

5 
 <div class="well">
 <h4>Side Widget Well</h4>
 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci
accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
 </div>
 </div>
</div>
<!-- /.row -->
<hr>